### ISSUE TITLE
out of date links in readme

### ISSUE THREAD

**Issue by xavier-taylor** [ir-nlp-csui/aksara#2]
On the readme some links are out of date:

Clone this [repository](https://github.com/bahasa-csui/aksara). git clone https://github.com/bahasa-csui/aksara

Should link to https://github.com/ir-nlp-csui/aksara etc.

Thanks for the tool :)

**Comment by ialfina** [comment]
Dear Xavier,
Thank you for your information. We have fixed the URL.
You are welcome.
